### ISSUE TITLE
Recline graph specs to vega view spec code

### ISSUE THREAD

**Issue by rgrp** [okfn/data.okfn.org-new#22]
* I think we focus on doing this *backend* with nodejs *before* code goes to frontend
* Should be very simple to test
* Support all recline graph options (see the recline flot graph documentation) - line graph, bar chart (both ways)
  * Multiple series (multiple lines)

How do we handle inlining the "resource" data - do we want to use datapackage-render-js?

**Comment by zelima** [comment]
Basic point:
- this should not need vega -  should just generate the vega spec not the vega graph
```
var reclineSpec = {
  graphType: ...
  etc
}
var vegaSpec = reclineToVega(reclineSpec);
```
vegaSpec should be vega spec missing the data referencing. Connecting to the resource data could be included here as per the datapackage-render-js approach or just left as separate.

**Comment by zelima** [comment]
@rgrp I came up with some script as a starting point. https://github.com/zelima/graph-views/blob/master/scripts/reclineToVegaSpec.js
I left comments about lines I am not clear, or need help. So, could you review it and leave your comments as well. Please review https://github.com/zelima/graph-views/commit/1a8af167f95c0ff9f9adfe072d4014af953bdb00#diff-be209b0528699dc573c338c5ed7cb773R51

**Comment by zelima** [comment]
@rgrp Added new function with tests: https://github.com/zelima/graph-views/blob/master/test/reclineToVegaSpec.js
Test looks like this:
![test-vega](https://cloud.githubusercontent.com/assets/15143785/17331432/ed7c9282-58db-11e6-87f1-0cf44f9f2cef.png)

**Comment by zelima** [comment]
@rgrp Assuming that recline spec looks like this: 
`spec = {"graphType": "lines","group": "ColumnX","series": ["ColumnY"]};`
I'm constructing **vega** spec depending on the variables above `graphtype`, `group` and `series`
But, Unlike recline spec, vega spec is more complicated:
```
vegaSpec = {
  signals: [{bar : foo}, {foo : bar}],  //ok
  data: [{bar : foo}, {foo : bar}],     //Not ok
  scales: [{bar : foo}, {foo : bar}],  // ok
  marks: [{bar : foo}, {foo : bar}],  // ok
  etc...
}
```
Difference is that recline spec does not need to declare info about **data**, when constructed, but vega spec does.
So since recline specifications does not carry any information about data (e.g:`path/to/data`, `url://to/data.com`, or `{"data": "itself"}`, etc...), I can not pass anything to vegaSpec: `vegaSpec.data = ???`

The test shown in previous comment fails because of this - info about data(url to `raw/github/data.csv` in this case) is undefined.

My question would be where/how to get info about data???
My guesses are:
 - define some new function (if there does not already exist one) that takes whole datapackage.json and outputs url/path to data or data itself.
 - pass another argument to function that makes transformation, when is called e.g: `reclineToVegaSpec(reclineSpec, infoAboutData)`
 - initially pass the whole datapackage.json to function that transforms recline to vega e.g:  `reclineToVegaSpec(datapackage.json)`

**Comment by rgrp** [comment]
@zelima as discussed on call we do not need to pass in info about data here. Once you have completed this and have a passing test, post link to repo here and we can close.

**Comment by zelima** [comment]
@rgrp removed any references to data from code. 
Link to repo: https://github.com/zelima/recline-to-vega-spec

**Comment by rgrp** [comment]
FIXED. See https://github.com/zelima/recline-to-vega-spec/issues for any further issues.
